### ISSUE TITLE
Empty cache folder

### ISSUE THREAD

**Issue by tordenflesk** [sentriz/gonic#148]
After 6 months my cache folder has grown to 78GB. Perhaps old transcoded files should be deleted?

**Comment by zpuskas** [comment]
I'm working on packaging this project for Gentoo. I'm considering adding a default cron job or systemd timer as a stop gap solution to delete old files form the cache until this is implemented in gonic itself. 

Would deleting cached files cause problems for gonic or will it simple recreate them as needed?

**Comment by sentriz** [comment]
> will it simple recreate them as needed?

:+1:  deleting them will be just fine

**Comment by mazzz1y** [comment]
For a workaround with Docker, I implement the following solution:

```yaml
version: "3"
services:
  gonic:
    image: sentriz/gonic:v0.15.2
    command: sh -c "while :; do sleep 3600; find /cache -type f -atime +90 -delete; done & gonic"
...
```

This approach is significantly simpler than installing cron or other methods that would require modifications to the original docker container.
