### ISSUE TITLE
How is this: GONIC_PROXY_PREFIX supposed to work?

### ISSUE THREAD

**Issue by polhaghverdian** [sentriz/gonic#198]
Hi,

I have tested and added the variable in my compose file. Like below:
It doesn't seem to work when i try to access the GUI. 

Changing this to GONIC_PROXY_PREFIX=/gonic, should result in: **mysite.com/gonic**  am I right?
However i just get: 404 page not found. Removing the prefix works as expected and I can access GUI from **mysite.com**

Tested with latest version: 0.14 and older one 0.12.

```
  gonic:
    image: sentriz/gonic:v0.14.0
    container_name: gonic
    hostname: gonic
    network_mode: bridge
    environment:
    - TZ
    - GONIC_PROXY_PREFIX=/gonic
    ports:
      - "80:80"
```

**Comment by sentriz** [comment]
hi! what reverse proxy are you using? could you share the relevant configs?

**Comment by polhaghverdian** [comment]
> hi! which reverse proxy are you using? could you share the relevant configs?

I haven't put it behind the proxy yet, because if I cant access the UI from the browser with the /gonic base_url applied directly, then there is no reason to complicate it further by adding it behind the proxy.

**Comment by sentriz** [comment]
the only thing that environment variable does is prefix internally generated links. so it's only useful (at least as far as I can think of) is behind a reverse path-based proxy. may I ask then what you are trying to achieve by setting the variable without a reverse proxy?

**Comment by polhaghverdian** [comment]
@sentriz My goal is to have gonic behind reverse proxy. However if I cant get the base_url to work without having it behind the proxy, this means that the internally generated links doesn't change. After setting the base-url i should then be able to access gonic on for example http://localhost/whatever/path/I/want.

**Comment by sentriz** [comment]
the way it works with gonic is, gonic will only serve incoming requests from `/`. it is the reverse proxy's job to serve requests from `/whatever/path` and forward them to gonic as if they were `/`. that works fine until you click a link in the UI. gonic has no idea about what path prefix the reverse proxy has setup so it assumes `/` and the reverse proxy probably 404s. that's where the env var comes in. with it gonic can generate links the reverse proxy can understand.

I'm typing this from my phone (after a few beers...) so perhaps just try it out with the reverse proxy? I've tested the path based proxying with nginx and it worked well then at least

**Comment by Whisprin** [comment]
I'm running into the same problem. Could you please reopen the issue?
(I'm using systemd instead of Docker to run gonic)

without `proxy-prefix` set I can access gonic from: http://localhost:4747 which redirects to http://localhost:4747/admin/login
=> The login page with the gonic logo is shown

with `proxy-prefix` set to `/gonic`, accessing http://localhost:4747 redirects to: http://localhost:4747/gonic/admin/home as expected, however:
=> A plain white page "404 page not found" is shown (without logo or footer)
![image](https://user-images.githubusercontent.com/3153136/230949936-30a5dc05-7a01-4584-8bea-e32d6a91dbb2.png)

When accessing gonic through the reverse proxy (Apache) the same error page is shown.
It seems as if gonic doesn't know about its own proxy prefix (which it has redirected to).

Addionally, accessing http://localhost:4747/admin/login with `proxy-prefix` set to `/gonic` doesn't result in 404, however serves a broken site (just the login form without css, or logo).
![image](https://user-images.githubusercontent.com/3153136/230949863-4f0a264b-e607-49d6-94b2-98a211a7b7cf.png)

**Comment by sentriz** [comment]
could you see if you have the same issue using the config mentioned here?

https://github.com/sentriz/gonic/wiki/reverse-proxy#nginx

**Comment by sentriz** [comment]
could you see if you have the same issue using the config mentioned here?

https://github.com/sentriz/gonic/wiki/reverse-proxy#nginx

**Comment by sentriz** [comment]
@Whisprin i just tested the [nginx config](https://github.com/sentriz/gonic/wiki/reverse-proxy#nginx) with GONIC_PROXY_PREFIX and it worked great. also i'm not so familiar with apache. but since it's working with nginx i can only assume it's an issue with your apache config

**Comment by sentriz** [comment]
all that gonic does with proxy-prefix is generates links to other resources with the "/gonic" prefix there. it does except that the reverse proxy strips the prefix before it gets to gonic (maybe that's the atypical bit? not sure)

here is a video it working with an nginx `/gonic` route and the proxy-prefix set to `gonic` too


https://user-images.githubusercontent.com/6832539/231511855-93eb8c34-b53e-4f1c-a9b2-46a2d01f3dc7.mp4

**Comment by Whisprin** [comment]
> it does except that the reverse proxy strips the prefix before it gets to gonic (maybe that's the atypical bit? not sure)

That's probablly it. And that's the reason why gonic can't be accessed direcly anymore (using localhost:4747 without the proxy) when PROXY_PREFIX is set.
Did you try to access http://localhost:4747/ ?

**Comment by sentriz** [comment]
oh! you are trying to visit gonic directly on it's native port. sorry i missed that bit

you're right that visiting natively with :4747 will redirect to `http://host:4747/gonic/admin/home` and that doesn't work since gonic doesn't have a `/gonic` route, the reverse proxy does

can't you just visit your reverse proxies port? eg if it's :80 then `http://host/gonic`

not sure what your use case of accessing gonic directly when you have reverse proxy set up

**Comment by Whisprin** [comment]
@sentriz This apache config is working for me. You can add it to the wiki.
```
<Location "/gonic" >
    ProxyPass http://localhost:4747
    ProxyPassReverse http://localhost:4747/gonic
    ProxyPassReverseCookiePath  "/"  "/gonic"
</Location>
```

Notice the difference between `ProxyPass` and `ProxyPassReverse`. This removes the prefix when sending requests to the application. With this out of the way: Accessing the server direcly without a proxy when proxy_prefix is set might be another (but related) conversation.

A typical use case is to access the server at :4747 directly from the home network and use the public host name from other networks. It helps with debugging and running/testing the service but more importantly:
Some home routers don't support[ hairpin routing/hairpinning](https://subspace.com/resources/hairpinning-and-traffic-backhauling), meaning https://mydomain.com/gonic isn't accessible when the client (DSub) is behind the same NAT as the server (Gonic). That's the reason why DSub supports two different server addresses: e.g. on home wifi use http://localserver:4747/, for other networks use: https://mydomain.com/gonic

**Comment by bytebone** [comment]
For the sake of completeness, I will add a little something regarding the Caddy reverse proxy. I've got a couple of apps running on my server, all in their respective paths. Gonic is the only app so far that expects the path variable to be removed before being handed to the gonic app. 

Usually, my caddy configs use the `handle /path` function to capture the path. For gonic, I need to use `handle_path /path` instead, which removes it before handing to the container. Otherwise, visiting the website results in a non-stop 303 redirect.

I will happily update the reverse proxy Caddy section with this little snippet, for both the path and no-path variations.

**Comment by markesss** [comment]
I'm using Traefik as my reverse proxy, just needed to add the stripprefix middleware in addition to the usual traefik labels.

Traefik will default to sending requests to Port 80 on the container, so if you're using **GONIC_LISTEN_ADDR** ENV to set a different port, be sure include the appropriate traefik custom service definition.

@sentriz - Here's an extension of the example dockerfile which supports Traefik for the Wiki.

```yaml
# example docker-compose.yml with Traefik Labels

version: "2.4"
services:
  gonic:
    image: sentriz/gonic:latest
    environment:
      - TZ
      # optionally, see more available env vars in the readme
      - GONIC_PROXY_PREFIX="gonic"	# set the proxy prefix within Gonic
# with traefik configured, this port mappings are no longer needed.
#    ports:
#      - 4747:80  
    volumes:
      - ./data:/data # gonic db etc
      - /path/to/music:/music:ro # your music
      - /path/to/podcasts:/podcasts # your podcasts
      - /path/to/playlists:/playlists # your playlists
      - /path/to/cache:/cache # transcode / covers / etc cache dir

    # set the following two sections if you've enabled jukebox
    group_add:
      - audio
    devices:
      - /dev/snd:/dev/snd
    labels:
      - "traefik.enable=true"	#enable Traefik for this Container
      - "traefik.http.routers.gonic.rule=(PathPrefix(`/gonic`))" 	
      - "traefik.http.routers.gonic.entrypoints=http"  # be sure to set this to the appropriate entrypoint for your configuration.
      - "traefik.http.routers.gonic.middlewares=gonicStripPrefix" 	# add the stripprefix middleware to the gonic router
      - "traefik.http.middlewares.gonicStripPrefix.stripprefix.prefixes=/gonic"	# configure stripprefix to strip the prefix on translation
```
