### ISSUE TITLE
Cannot update remote players databases

### ISSUE THREAD

**Issue by AlessandroZanatta** [sentriz/gonic#271]
Hi,

I'm currently receiving a panic every time I try to update the library of a subsonic player (official Android app).
In particular, the following error is logged:

```
2022/12/12 10:37:08 response  200  for `/rest/getPlaylists.view?c=android&p=REDACTED&u=kalex&v=1.2.0`
2022/12/12 10:37:10 response  200  for `/rest/getMusicFolders.view?c=android&p=REDACTED&u=kalex&v=1.2.0`
2022/12/12 10:33:53 http: panic serving 172.18.0.3:45892: runtime error: index out of range [1] with length 1
goroutine 541 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1850 +0xb8
panic({0xb0a180, 0x400078e6a8})
	/usr/local/go/src/runtime/panic.go:890 +0x260
go.senan.xyz/gonic/server/ctrlsubsonic.getMusicFolder({0x400024ac40, 0x1, 0xcb2f20?}, 0x0?)
	/src/server/ctrlsubsonic/handlers_common.go:40 +0xcc
go.senan.xyz/gonic/server/ctrlsubsonic.(*Controller).ServeGetIndexes(0x40004721b0, 0x40009aca00)
	/src/server/ctrlsubsonic/handlers_by_folder.go:28 +0x198
go.senan.xyz/gonic/server/ctrlsubsonic.(*Controller).H.func1({0xcb9870, 0x40000a45e8}, 0x40009dd518?)
	/src/server/ctrlsubsonic/ctrl.go:107 +0x34
net/http.HandlerFunc.ServeHTTP(0xcba380?, {0xcb9870?, 0x40000a45e8?}, 0xcb22f0?)
	/usr/local/go/src/net/http/server.go:2109 +0x38
go.senan.xyz/gonic/server/ctrlsubsonic.(*Controller).WithUser.func1({0xcb9870, 0x40000a45e8}, 0x40009ac900)
	/src/server/ctrlsubsonic/middleware.go:87 +0x4a0
net/http.HandlerFunc.ServeHTTP(0x40009c0620?, {0xcb9870?, 0x40000a45e8?}, 0xa6eca0?)
	/usr/local/go/src/net/http/server.go:2109 +0x38
go.senan.xyz/gonic/server/ctrlsubsonic.(*Controller).WithRequiredParams.func1({0xcb9870, 0x40000a45e8}, 0x40009ac900)
	/src/server/ctrlsubsonic/middleware.go:50 +0xcc
net/http.HandlerFunc.ServeHTTP(0xcba380?, {0xcb9870?, 0x40000a45e8?}, 0xcb2398?)
	/usr/local/go/src/net/http/server.go:2109 +0x38
go.senan.xyz/gonic/server/ctrlsubsonic.(*Controller).WithParams.func1({0xcb9870, 0x40000a45e8}, 0x40009ac800)
	/src/server/ctrlsubsonic/middleware.go:33 +0x144
net/http.HandlerFunc.ServeHTTP(0xafacc0?, {0xcb9870?, 0x40000a45e8?}, 0x1c?)
	/usr/local/go/src/net/http/server.go:2109 +0x38
go.senan.xyz/gonic/server/ctrlbase.(*Controller).WithCORS.func1({0xcb9870, 0x40000a45e8}, 0x40009ac800)
	/src/server/ctrlbase/ctrl.go:106 +0x278
net/http.HandlerFunc.ServeHTTP(0x400037a400?, {0xcb9870?, 0x40000a45e8?}, 0x76a784?)
	/usr/local/go/src/net/http/server.go:2109 +0x38
go.senan.xyz/gonic/server/ctrlbase.(*Controller).WithLogging.func1({0xcb9d20?, 0x40009680e0}, 0x40009ac800)
	/src/server/ctrlbase/ctrl.go:83 +0xa0
net/http.HandlerFunc.ServeHTTP(0x40009ac700?, {0xcb9d20?, 0x40009680e0?}, 0x29bad7a09c?)
	/usr/local/go/src/net/http/server.go:2109 +0x38
github.com/gorilla/mux.(*Router).ServeHTTP(0x400015e000, {0xcb9d20, 0x40009680e0}, 0x40009ac600)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1a4
net/http.serverHandler.ServeHTTP({0x40004c32c0?}, {0xcb9d20, 0x40009680e0}, 0x40009ac600)
	/usr/local/go/src/net/http/server.go:2947 +0x2cc
net/http.(*conn).serve(0x40002a8000, {0xcba380, 0x40004c30e0})
	/usr/local/go/src/net/http/server.go:1991 +0x544
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3102 +0x43c
```

I've tried to understand if this error was related to my music library, but after removing everything from it and updating gonic's library the error persisted. Even stranger, I had this error appear some time ago. After a while I tried other software for my music, but I eventually came back to gonic. For some time, everything worked. Then this error came back.
I don't really know how this error can be reproduced, but maybe the trace is informative enough for someone who's familiar with the code base (and Go).

I'm using the following docker-compose, if it is of any help. It should be fairly similar to the suggested one anyway.
````
version: "3"

services:
  gonic:
    image: sentriz/gonic:latest
    volumes:
      - ./data:/data         # gonic db etc
      - /srv/music:/music:ro    # your music
      - ./podcasts:/podcasts # your podcasts
      - ./cache:/cache       # transcode / covers / etc cache dir
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gonic.rule=Host(`myhostname`)"
      - "traefik.http.routers.gonic.entrypoints=websecure"
      - "traefik.http.routers.gonic.tls=true"
      - "traefik.http.services.gonic.loadbalancer.server.port=80"
    networks:
      - traefik-net
    restart: unless-stopped
    # set the following two sections if you've enabled jukebox
    # group_add:
    # - audio
    # devices:
    # - /dev/snd:/dev/snd

networks:
  traefik-net:
    external: true
```
