### ISSUE TITLE
Gonic not starting on Docker?

### ISSUE THREAD

**Issue by jmbannon** [sentriz/gonic#281]
:wave: 
Trying to run Gonic via Docker but it doesn't look like it's starting and can't access the web GUI. Here's the logs:
```
gonic              | 2023/01/12 23:21:55 starting gonic v0.15.2
gonic              | 2023/01/12 23:21:55 provided config
gonic              | 2023/01/12 23:21:55     cache-path                /cache
gonic              | 2023/01/12 23:21:55     config-path               
gonic              | 2023/01/12 23:21:55     db-path                   /data/gonic.db
gonic              | 2023/01/12 23:21:55     genre-split               
gonic              | 2023/01/12 23:21:55     http-log                  true
gonic              | 2023/01/12 23:21:55     jukebox-enabled           false
gonic              | 2023/01/12 23:21:55     jukebox-mpv-extra-args    
gonic              | 2023/01/12 23:21:55     listen-addr               127.0.0.1:4747
gonic              | 2023/01/12 23:21:55     music-path                /Music/Tagged, /Music/TaggedManual
gonic              | 2023/01/12 23:21:55     podcast-path              /podcasts
gonic              | 2023/01/12 23:21:55     podcast-purge-age         0
gonic              | 2023/01/12 23:21:55     proxy-prefix              
gonic              | 2023/01/12 23:21:55     scan-at-start-enabled     false
gonic              | 2023/01/12 23:21:55     scan-interval             0
gonic              | 2023/01/12 23:21:55     scan-watcher-enabled      false
gonic              | 2023/01/12 23:21:55     tls-cert                  
gonic              | 2023/01/12 23:21:55     tls-key                   
gonic              | 2023/01/12 23:21:55     version                   false
gonic              | 2023/01/12 23:21:55 starting job 'podcast refresher'
gonic              | 2023/01/12 23:21:55 starting job 'http'
gonic              | 2023/01/12 23:21:55 starting job 'session clean'
```
And my docker compose:
```
  gonic:
    image: sentriz/gonic:latest
    container_name: gonic
    environment:
      - TZ=America/Los_Angeles
      - "GONIC_MUSIC_PATH=/Music/Tagged,/Music/TaggedManual"
      - "GONIC_LISTEN_ADDR=127.0.0.1:4747"
    user: ${AIRSONIC_PUID}:${AIRSONIC_PGID}
    expose:
      - 80
    ports:
      - 4747:4747
    volumes:
      - ${APP_PATH}/gonic/data:/data
      - ${APP_PATH}/gonic/cache:/cache
      - ${NAS_PATH}/Music/Playlists/MusicBee/Exported Playlists:/var/playlists:ro
      - ${NAS_PATH}/Music/Tagged:/Music/Tagged:ro
      - ${NAS_PATH}/Music/TaggedManual:/Music/TaggedManual:ro
```
I've tried with and without `expose` but no luck. Any help would be great, thanks!
