### ISSUE TITLE
Podcast: could not create feed: no audio in feed item

### ISSUE THREAD

**Issue by mattiasghodsian** [sentriz/gonic#376]
gonic version: 0.15.2
docker tag: sentriz/gonic:latest

docker-compose.yml
```yml
version: "2.4"
services:
  gonic:
    image: sentriz/gonic:latest
    command: sh -c "while :; do sleep 3600; find /cache -type f -atime +90 -delete; done & gonic"
    ports:
      - 4533:80
    volumes:
    ....
    environment:
      - GONIC_SCAN_INTERVAL=5
      - GONIC_GENRE_SPLIT=/
      - GONIC_SCAN_WATCHER_ENABLED=1
    group_add:
      - audio
    devices:
      - /dev/snd:/dev/snd

    restart: unless-stopped
```

I'm trying to add a feed [darknetdiaries](https://feeds.megaphone.fm/darknetdiaries) to gonic and returns `could not create feed: no audio in feed item`
