### ISSUE TITLE
First install I cant login :error saving session: securecookie: hash key is not set

### ISSUE THREAD

**Issue by gerroon** [sentriz/gonic#408]
Hi

I am using docker-compose and I cant open the webpage after install. I am using it locally in my wifi network.

This is the message I get in the browser

`error saving session: securecookie: hash key is not set`

I am using the default compose on debian testing, except the music path

```
version: "2.4"
services:
  gonic:
    image: sentriz/gonic:latest
    environment:
      - TZ
      # optionally, see more available env vars in the readme
    ports:
      - 4747:80
    volumes:
      - ./data:/data # gonic db etc
      - /path/to/music:/music:ro # your music
      - /path/to/podcasts:/podcasts # your podcasts
      - /path/to/playlists:/playlists # your playlists
      - /path/to/cache:/cache # transcode / covers / etc cache dir

    # set the following two sections if you've enabled jukebox
    group_add:
      - audio
    devices:
      - /dev/snd:/dev/snd

```

```
gonic_1  | 2023/11/11 07:26:49 starting gonic v0.16.1
gonic_1  | 2023/11/11 07:26:49 provided config
gonic_1  | 2023/11/11 07:26:49     cache-path                /cache
gonic_1  | 2023/11/11 07:26:49     config-path
gonic_1  | 2023/11/11 07:26:49     db-path                   /data/gonic.db
gonic_1  | 2023/11/11 07:26:49     exclude-pattern
gonic_1  | 2023/11/11 07:26:49     expvar                    false
gonic_1  | 2023/11/11 07:26:49     genre-split
gonic_1  | 2023/11/11 07:26:49     http-log                  true
gonic_1  | 2023/11/11 07:26:49     jukebox-enabled           false
gonic_1  | 2023/11/11 07:26:49     jukebox-mpv-extra-args
gonic_1  | 2023/11/11 07:26:49     listen-addr               :80
gonic_1  | 2023/11/11 07:26:49     multi-value-album-artist  none
gonic_1  | 2023/11/11 07:26:49     multi-value-artist        none
gonic_1  | 2023/11/11 07:26:49     multi-value-genre         none
gonic_1  | 2023/11/11 07:26:49     music-path                /music
gonic_1  | 2023/11/11 07:26:49     playlists-path            /playlists
gonic_1  | 2023/11/11 07:26:49     podcast-path              /podcasts
gonic_1  | 2023/11/11 07:26:49     podcast-purge-age         0
gonic_1  | 2023/11/11 07:26:49     proxy-prefix              /
gonic_1  | 2023/11/11 07:26:49     scan-at-start-enabled     false
gonic_1  | 2023/11/11 07:26:49     scan-interval             0
gonic_1  | 2023/11/11 07:26:49     scan-watcher-enabled      false
gonic_1  | 2023/11/11 07:26:49     tls-cert
gonic_1  | 2023/11/11 07:26:49     tls-key
gonic_1  | 2023/11/11 07:26:49     version                   false
gonic_1  | 2023/11/11 07:26:49 starting job "http"
gonic_1  | 2023/11/11 07:26:49 starting job "session clean"
gonic_1  | 2023/11/11 07:26:49 starting job "podcast refresh"
gonic_1  | 2023/11/11 07:26:57 response  303  GET /
gonic_1  | 2023/11/11 07:26:57 error saving session: securecookie: hash key is not set
gonic_1  | 2023/11/11 07:26:57 response  303  GET /home
gonic_1  | 2023/11/11 07:26:57 response  500  GET /login
gonic_1  | 2023/11/11 07:26:57 response  303  GET /favicon.ico
gonic_1  | 2023/11/11 07:27:06 response  500  GET /login
gonic_1  | 2023/11/11 07:27:09 response  500  GET /login
gonic_1  | 2023/11/11 07:27:13 response  500  GET /login
gonic_1  | 2023/11/11 07:27:13 response  303  GET /favicon.ico
gonic_1  | 2023/11/11 07:27:14 response  500  GET /
gonic_1  | 2023/11/11 07:27:22 response  500  GET /
gonic_1  | 2023/11/11 07:27:22 response  303  GET /favicon.ico



```
