### ISSUE TITLE
jukebox locks and shuffling

### ISSUE THREAD

**Issue by niawag** [sentriz/gonic#411]
gonic version: 0.16.1
if from docker, docker tag: latest arm64

Hi, I'm using gonic to stream music to DSub and to play music locally with the jukebox and it's really awesome !
I'm having an issue with the jukebox mode: after some time (don't know how much) my phone lose the connection to the server. I can still stream songs to my phone but I can't control the server. If it's playing songs it keeps playing them till the end of the playlist.
It seems it occurs when a big playlist (a few hundred songs) is played but I may not have noticed it other times.

Gonic logs (docker logs gonic) are empty but working (the logs are populated if i run a scan from the webui).
I activated mpv logs and can't find anythin relevant, as I've said, the songs keep being played locally ant mpv logs show that.

Here is my docker compose setup: 
```
gonic:
    container_name: gonic
    platform: linux/arm64 #necessary because on coreelec, the os is 32 bits but only arm64 images works
    image: sentriz/gonic:latest
    environment:
      - TZ=Europe/Paris
      - GONIC_HTTP_LOG=false
      - GONIC_JUKEBOX_ENABLED=true
      - GONIC_PLAYLISTS_PATH=/playlists
      - GONIC_MULTI_VALUE_ALBUM_ARTIST=multi
      - GONIC_JUKEBOX_MPV_EXTRA_ARGS="--log-file=/data/mpv_logs"
    ports:
      - 3080:80
    volumes:
      - ./gonic/data:/data
      - /storage/mnt/multimedia/mp3/_Playlists/:/playlists
      - /storage/mnt/multimedia/mp3/:/music:ro
      - ./gonic/cache:/cache 
      - /run/pulse/:/run/pulse/
```
I don't recall having this issue with gonic 0.15, I'm willing to test it but I don't know how to store the logs as they seem to disappear from docker logs after a bit of time. Do you know what I could do ?

**Comment by sentriz** [comment]
strange . are you running behind a reverse proxy?

**Comment by niawag** [comment]
Yes, gonic is behind a traefik proxy running on another server. The config
is pretty simple:
```
http:
    routers:
      gonic-rtr:
        rule: "Host(`gonichostname.wtf`)"
        entryPoints:
          - https
        service: gonic-svc
        tls:
          certResolver: dnsovh
    services:
      gonic-svc:
        loadBalancer:
          servers:
            - url: "http://192.168.0.99:3080"
```

Le dim. 12 nov. 2023, 19:23, Senan Kelly ***@***.***> a
écrit :
