### ISSUE TITLE
Playlist does not work when the file resides in a music-path that is not the first

### ISSUE THREAD

**Issue by jmbannon** [sentriz/gonic#437]
gonic version: v0.16.2

When reading from a playlist where a track resides in a music-path that is not the first one, it says it cannot be found:
```
2023/12/21 15:04:25 error looking up path "/Music/TaggedManual/El Jazzy Chavo/[2021] Strangelands/09 - A Distant Star.mp3": not found
2023/12/21 15:04:25 error looking up path "/Music/TaggedManual/El Jazzy Chavo/[2018] Redirections/04 - Dreams In A Sewer.mp3": not found
```

Docker-compose:
```
  gonic:
    container_name: gonic
    image: sentriz/gonic:latest
    environment:
      - TZ=America/Los_Angeles
      - GONIC_MUSIC_PATH=/Music/Tagged,/Music/TaggedManual
      - GONIC_MULTI_VALUE_GENRE=multi
      - GONIC_MULTI_VALUE_ARTIST=multi
      - GONIC_MULTI_VALUE_ALBUM_ARTIST=multi
      - GONIC_LISTEN_ADDR=0.0.0.0:4747
      # optionally, see more available env vars in the readme
    ports:
      - 4747:4747
    volumes:
      - ${APP_PATH}/gonic:/data
      - ${NAS_PATH}/Music/Playlists/MusicBee/Exported Playlists:/playlists
      - ${NAS_PATH}/Music/Tagged:/Music/Tagged:ro
      - ${NAS_PATH}/Music/TaggedManual:/Music/TaggedManual:ro
  ```
  
Maybe also related, but in DSub when I try to view the `TaggedManual` folder, it results in no data. However, if a select All folders, stuff in `TaggedManual` is there.
