### ISSUE TITLE
Transcoding seemingly does nothing

### ISSUE THREAD

**Issue by AlicesReflexion** [sentriz/gonic#463]
gonic version: 0.16.2

if from docker, docker tag: latest

I have my client, Symfonium, request a max bitrate of 192kbps. 
![image](https://github.com/sentriz/gonic/assets/6933425/f5918be2-b997-496a-b8e6-7c294019abd8)

MaxBitRate is successfully passed to Gonic, I can see it in the log:

![image](https://github.com/sentriz/gonic/assets/6933425/65b20fa3-17e9-4c46-9f5c-e2c424024101)

Gonic has transcoding profiles, for both * and the Synfonium client:

![image](https://github.com/sentriz/gonic/assets/6933425/7642b6fb-285f-4d19-8d95-4dacb3d1f8a0)

The file that Symfonium receives back, however, is a 24-bit FLAC, at a whopping 1570kbps:

![image](https://github.com/sentriz/gonic/assets/6933425/b7e56274-fcd7-44db-b369-39f32b094e53)

Docker-compose.yml is as follows
```
services:
  gonic:
    image: sentriz/gonic:latest
    environment:
      - TZ
      - GONIC_MULTI_VALUE_GENRE=multi
      - GONIC_MULTI_VALUE_ARTIST=multi
      - GONIC_MULTI_VALUE_ALBUM_ARTIST=multi
    ports:
      - 4747:80
    volumes:
      - /home/alice/.gonic:/data
      - /home/alice/.playlists:/playlists
      - /home/alice/disks/encrypted/Music:/music:ro
      - /home/alice/.cache/gonic:/cache
```

The docker container seems to have the ffmpeg binary
```
sudo docker exec -it alice_gonic_1 "ffmpeg"
ffmpeg version 6.0.1 Copyright (c) 2000-2023 the FFmpeg developers
```

So, at this point, I'm kind of at a loss as to what could be going wrong.
