### ISSUE TITLE
Can't play Web Radio in Jukebox mode: error creating playlist items: find track by id: not found

### ISSUE THREAD

**Issue by frabnet** [sentriz/gonic#481]
Hi everyone, I'm trying to use Gonic in Jukebox mode to play Internet Radio streams locally on the server.

gonic version: v0.16.3

Built with docker-compose.yml:

```
version: "2.4"
services:
  gonic:
    image: sentriz/gonic:latest
    environment:
      - TZ = Europe/Rome
      - GONIC_JUKEBOX_ENABLED=true
      - GONIC_JUKEBOX_MPV_EXTRA_ARGS='--audio-device=alsa/default:CARD=Set"
      #force the correct audio card if multiple are present, found running mpv --audio-device=help inside the container
    ports:
      - 4747:80
    volumes:
      - ./data:/data # gonic db etc
      - ./music:/music:ro # your music
      - ./podcasts:/podcasts # your podcasts
      - ./playlists:/playlists # your playlists
      - ./cache:/cache # transcode / covers / etc cache dir
    group_add:
      - audio
    devices:
      - /dev/snd:/dev/snd
```

Added two radio stations on the Gonic web interface:

- Radio Asiago http://onair18.xdevel.com:8136
- Radio KissKiss http://ice07.fluidstream.net:8080/KissKiss.mp3

Using DSub Android Client, local music is played correctly, but when I play Web Radio it doesn't ouput any audio, and following error is logged:

```
gonic-1  | 2024/03/11 13:51:13 response  200  GET /jukeboxControl?u=admin&s=xxxxxxxxxxxxxxxxxxxxxxxxxx&t=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&v=1.2.0&c=DSub&action=status
gonic-1  | 2024/03/11 13:52:08 response  200  GET /jukeboxControl?u=admin&s=xxxxxxxxxxxxxxxxxxxxxxxxxx&t=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&v=1.2.0&c=DSub&action=status
gonic-1  | 2024/03/11 13:52:13 response  200  GET /jukeboxControl?u=admin&s=xxxxxxxxxxxxxxxxxxxxxxxxxx&t=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&v=1.2.0&c=DSub&action=set
gonic-1  | 2024/03/11 13:52:13 subsonic error code 0: error creating playlist items: find track by id: not found

```

Things I've tried:
- Without Jukebox mode the radio streams are played correcly in DSub
- Changed a lot of internet radio urls with no success
- Run MPV direclty inside the container and it outputs music correctly  `# mpv -audio-device=alsa/default:CARD=Set http://onair18.xdevel.com:8136/`

Any clue if this is a Gonic bug or other test to do?
