### ISSUE TITLE
"Recent folders" list in the web UI should limit folder name length

### ISSUE THREAD

**Issue by spijet** [sentriz/gonic#49]
I noticed a weird thing with web UI — if a recently added folder has a very long name, it'll cause the list to overflow and "break through" its container:
![20200324_113003](https://user-images.githubusercontent.com/14221126/77385368-def67c00-6dc2-11ea-9af7-3551a679132e.png)

It should be possible to limit length of these entries either in the backend (by truncating the folder name to some pre-defined length) or by using CSS:
```css
.ellipsis {
  text-overflow: ellipsis;

  /* Required for text-overflow to do anything */
  white-space: nowrap;
  overflow: hidden;
}
```
The second approach will allow to show full folder name on mouseover with some kind of a tooltip.
