### ISSUE TITLE
`artists`, `albumartists`, and `genres` with picard

### ISSUE THREAD

**Issue by alscaldas** [sentriz/gonic#528]
gonic version: v0.16.4 (Docker nightly)

I believe that either the feature multi genres, artists and album artists isn't working properly to me or I didn't understand how to corretly tag my audio library.

My audio files are mostly FLAC (some 95% flac, the rest mp3 and m4a lossless). I use Picard to tag them and I believe that they're correctly tagged because when I use for example MPD (which is what I use most of time on my desktop) it works correctly.

What I mean is: If a album has 3 different genres MPD shows me (in fact, ncmpcpp) shows me the album in 3 different places if I search by genres. The same goes to artists and album artists. I understood that Gonic worked the same way (and I know it works because I read successfull cases in both the installation instructions and the closed issues). But it isn't working to me...

I don't like albums that have something as "Artist A featuring Artist B". I do prefer them as being completely separate entities (Artist A and Artist B as multiple Artists and, if the case, Album Artists also), and if I understood it right, the flac metadata supports it and also gonic supports it. In fact, I love the fact that gonic is capable of doing this, because the other servers I tested apparently don't do.

Anyway, here is my docker-compose.yml file:

```
services:
  gonic2:
    image: sentriz/gonic:nightly
    container_name: gonic2
    restart: unless-stopped
    environment:
      GONIC_MULTI_VALUE_GENRE: "multi"
      GONIC_MULTI_VALUE_ARTIST: "multi"
      GONIC_MULTI_VALUE_ALBUM_ARTIST: "multi"
      GONIC_SCAN_INTERVAL: 5
      GONIC_SCAN_WATCHER_ENABLED: 1
      # optionally, see more available env vars in the readme
    #env_file: 
      #- stack.env
    ports:
      - 4748:80
    volumes:
      - /home/myuser/Docker/gonic2/data:/data # gonic db etc
      - /mnt/Storage/Temp/Músicas:/music:ro # your music
      #- /path/to/podcasts:/podcasts # your podcasts
      - /home/myuser/Docker/gonic2/playlists:/playlists # your playlists
      - /home/myuser/Docker/gonic2/cache:/cache # transcode / covers / etc cache dir

    # set the following two sections if you've enabled jukebox
    #group_add:
    #  - audio
    #devices:
    #  - /dev/snd:/dev/snd
```

The following images show on the left side 2 examples of how I usually tag my files. Reading [this](https://github.com/sentriz/gonic/issues/416) I noticed that gonic expects to find albumartists and artists in order to work.

![001](https://github.com/user-attachments/assets/6f8fd5b2-144d-4182-8d95-16a1b16578ca)
![002](https://github.com/user-attachments/assets/6eed4bdf-a764-4316-94dd-db96ee3a1dde)

As I read about the Picard tag scripting possibilities I tried to use this:

```
$setmulti(artists,%artists%)
$setmulti(albumartists,%albumartists%)
$setmulti(genre,%genre%)
```

But in the 2 cases I mentioned in the images, it works in one of them but not in the other. Also, genres don't work at all.

Here is an example:
![003](https://github.com/user-attachments/assets/3e88d33d-1421-47dc-b723-28fa902b1ded)

As seen on the first attachment, the album "A Panela do Diabo" is supposed to have 4 genres ("Latin", "New Wave", "Rock" and "Rock and Roll") but only "Latin" is detected. 

![004](https://github.com/user-attachments/assets/02463361-40bb-4a7b-bc3d-f3494fadbdfb)

As for the second attachment,  "Americana", it's supposed to have 2 artists and 2 album artists, but if I go to "Artists" I don't see "The Crazy Horse". I see only "Neil Young".

I believe there's something I still didn't get about the right way to tag these. Could you please take I look if I'm doing something wrong and, if that's the case, point me in the right direction?
